name: sandbox
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  line_awesome_flutter: ^2.0.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.7
  firebase_core: ^2.4.1
  auto_route: ^5.0.4
  json_annotation: ^4.8.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  flutter_hooks: ^0.18.6
  http: ^0.13.5
  image_picker: ^0.8.7
  stacked: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  stacked_generator: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
