include: package:very_good_analysis/analysis_options.4.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    always_declare_return_types: true
    always_specify_types: true
    omit_local_variable_types: false
