name: five_on_4_by_packages
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  dio: ^4.0.6
  logger: ^1.1.0
  path_provider: ^2.0.11
  formz: ^0.4.1
  infinite_scroll_pagination: ^3.2.0
  flutter_svg:
    ^1.1.6

    # TODO dont use this
  # core_feature:
  #   path: package/core_feature
  # players_feature:
  #   path: package/players_feature
  # weather_feature:
  #   path: package/weather_feature
  # auth_feature:
  #   path: package/auth_feature

dev_dependencies:
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svg/
