name: core_feature
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  players_feature:
    path: ../players_feature
  weather_feature:
    path: ../weather_feature
  auth_feature:
    path: ../auth_feature

  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  dio: ^4.0.6
  logger: ^1.1.0
  path_provider: ^2.0.11
  formz: ^0.4.1
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
flutter:
